# Generated by Django 5.0.1 on 2024-02-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
