# Generated by Django 5.0.1 on 2024-02-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_member_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.ForeignKey(default='beginner', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.status'),
        ),
    ]
