# Generated by Django 5.0.1 on 2024-02-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
