# Generated by Django 5.0.1 on 2024-02-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_member_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('name',), 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'ordering': ('flower',), 'verbose_name_plural': 'Varieties'},
        ),
    ]
