# Generated by Django 4.1 on 2024-02-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.status'),
        ),
    ]
