from django.urls import path


from club.views import (
    index,
    StatusListView,
    MemberListView, MemberDetailView,
    MemberCreateView, MemberDeleteView, MemberUpdateView,
    VarietyListView, VarietyCreateView, VarietyUpdateView, VarietyDeleteView,
    VioletListView, VioletDetailView,
    VioletCreateView, VioletUpdateView, VioletDeleteView,
    PostCreateView, PostUpdateView,
    AssignVioletView,
)


urlpatterns = [
    path("", index, name="index"),
    path("varietes/",
         VarietyListView.as_view(),
         name="variety-list"),
    path("varietes/create/",
         VarietyCreateView.as_view(), name="variety-create",),
    path("varietes/update/<int:pk>/",
         VarietyUpdateView.as_view(), name="variety-update",),
    path("varietes/delete/<int:pk>/",
         VarietyDeleteView.as_view(), name="variety-delete",),
    path("statuses/",
         StatusListView.as_view(),
         name="status-list"),
    path("members/",
         MemberListView.as_view(),
         name="member-list"),
    path("members/<int:pk>/",
         MemberDetailView.as_view(),
         name="member-detail"),
    path("members/create/",
         MemberCreateView.as_view(),
         name="member-create"),
    path("members/update/<int:pk>/",
         MemberUpdateView.as_view(),
         name="member-update"),
    path("members/delete/<int:pk>",
         MemberDeleteView.as_view(),
         name="member-delete"),
    path("violets/",
         VioletListView.as_view(),
         name="violet-list"),
    path("violets/<int:pk>/",
         VioletDetailView.as_view(),
         name="violet-detail"),
    path("violets/create/",
         VioletCreateView.as_view(),
         name="violet-create"),
    path("violets/update/<int:pk>/",
         VioletUpdateView.as_view(),
         name="violet-update"),
    path("violets/delete/<int:pk>/",
         VioletDeleteView.as_view(),
         name="violet-delete"),
    path("posts/create/",
         PostCreateView.as_view(),
         name="post-create"),
    path("posts/update/<int:pk>/",
         PostUpdateView.as_view(),
         name="post-update"),
    path("violets/<int:pk>/assign/",
         AssignVioletView.as_view(),
         name="assign-violet"),
]

app_name = "club"
